### ISSUE TITLE
TensorOverCentroid crash

### ISSUE THREAD

**Issue by algeboy** [thetensor-space/TameGenus#10]
There was a bug that if you gave a to tame genus a bimap whose centroid was not a field and "Cent:=true" was set to be used, it would call `TensorOverCentroid` and this would crash because that command only appears to work over fields.

Posting the bug here and closing it, just incase it later needs to re-opened because my work around isn't right.

**Comment by algeboy** [comment]
Fixed by first checking of centroid is a field, and if not, skipping centoird.  Added feature request to add centroid over any ring in the future.

**Comment by joshmaglione** [comment]
Can you post the example? 

If it failed to do anything, my guess is that it must have been a decomposable group. That is, the centroid was not a local algebra.

**Comment by algeboy** [comment]
The example was happening about 1/3 of all random calls to `TGRandomGenus(3,4,2);`  A super confusing part of this function is that you could create a random TG 2 group then ask `Genus(G)` and it would not be genus 2.  So along with the fix I have now added a loop in `TGRandomGenus` to stay in the loop until it actually has a group of the targeted genus.

**Comment by joshmaglione** [comment]
I don't understand why this got closed. Is this a problem with `TensorOverCentroid` or `TGRandomGenus`? Last I checked `TensorOverCentroid` could handle finite local algebras as centroids. Are you encountering something else?

From your response, the only groups that should pop up out of `TGRandomGroup(3, 4, 2)` are a direct product of two Heisenberg groups over GF(3) or a Heisenberg group over GF(9). The latter should be handled, and the former is decomposable.

**Comment by algeboy** [comment]
Fine if it handles a local algebra it can be relaxed to that.  But TGRand shouldn't by default return examples that later crash commands like TGSignature.  It is confusing if our own randomized examples don't work in the system.  But think this is closed, its a feature we might add in the future but its not crashing anymore and that was the bug.

**Comment by joshmaglione** [comment]
> Fine if it handles a local algebra it can be relaxed to that.

This is what I'm claiming, but you were writing it only handles fields. Do you have an example? There could, indeed, be a bug.

**Comment by joshmaglione** [comment]
Here's what I mean. This is all the code does.

```
C := Centroid(t);
J, S := WedderburnDecomposition(C);
...
require IsCommutative(S) : "Tensor is not fully nondegenerate.";
cyclic_check, X := IsCyclic(S);
require cyclic_check : "Centroid must be a commutative local ring.";
require IsIrreducible(MinimalPolynomial(X)) : "Tensor must be indecomposable.";
```

Then it goes on to write the tensor over the `S`.

**Comment by algeboy** [comment]
Ok, I think I missed that it was irreducible applied to Wedderburn complement not C.  So that's resolved.Then yes, I see, testing that is a field is stronger than needed and it should test less.  But it needs some guarding because the testing that is being done was causing uncaught exceptions, and this is not helping give this package a clean bill of health.  That the placement of the guard solves this but it is as you say guarding against local rings when it should only guard against decomposable.

**Comment by joshmaglione** [comment]
Yeah, I agree. I didn't---and still don't---have a great solution to this. How about a `try` `catch` statement? An error needs to be raised,  but I guess it's a question about how helpful it is to the user?

**Comment by algeboy** [comment]
Now that we have templates we could use Either monads.  No strong opinion, just saying.  It would take a minor re-education of magma users to know how to use the return of None/Some or Left/Right but its our package we could just do what's best.  Lets involve Pete on that discussion.

**Comment by joshmaglione** [comment]
Here's a solution I think should be considered. It has an advantage of being a "simple" solution. This was what I was getting at earlier with my try catch suggestion.

Suppose `t` is a tensor that passes all initial tests. That is, we're now ready to write the tensor over its centroid. Let's assume we've already refactored this code, so it's a stand-alone function.
```scala
// TYPE: (t: TenSpcElt, Cent: BoolElt): TenSpcElt, Hmtp
__TensorOnCent := function(t, Cent)
    try
        require Cent : "If set to false, we catch.";
        s, H := TensorOverCentroid(t);
        return s, H;
    catch err
        /* Create identity autotopism, H, on t */
        return t, H;
    end try;
end function;
```

As we factor out radicals and do other simple checks before this stage, we can be fairly certain that an error that arises is likely caused because `t` is decomposable. But regardless of what the error is, all the function knows is that it could not write `t` over its centroid, so it will proceed without it. 

After this, the code tests that the dimension of the codomain of the tensor is <= 2. Of course, the genus (over the residue field) can only be smaller. But getting the smallest genus does one of two things:
1. gives us a better algorithm to run, or
2. brings the tensor into the domain of our function. 

If the tensor fails the dimension check, then the user sees that the group/tensor does not have tame genus. This may be incorrect! But at least our `Genus` function would give the same report. We should definitely remark on this in the documentation as I did not adequately do this when I wrote it. 

#### What does this fix? 
If you have an exponent *p* class 2 group *G* of order *p^{d + 2}*, then `TGAutomorphismGroup` will return the automorphism group of *G*. Before the fix from @algeboy, it was possible to encounter an error even in this case (decomposable groups). 

#### What does this NOT fix?
If you're calling `Genus2Signature` then it is a *requirement* that you hand in an indecomposable genus 2 group. In particular, if this "fix" was applied to `Genus2Signature` then you cannot guarantee the labels are canonical. Therefore, if the function cannot write the tensor over its centroid, an error needs to be returned. So if a user is interfacing with TameGenus through the signature, then issues still arise. 

Until we have a `IndecomposableSubtensors` function for a tensor, this will always be an issue with `Genus2Signature`. To pull an idea from your other post, should we incorporate "indecomposable" in the name? `Genus2Signature` is already long. I don't know. 

Maybe @galois60 can chime in.

**Comment by joshmaglione** [comment]
See Issue #17.
